name: tcp_socket_flutter
description: TCP Socket for Flutter.
version: 0.0.5
homepage: https://github.com/nghetien/tcp_socket_flutter

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  dart_ipify: ^1.1.1
  network_info_plus: ^3.0.1
  device_info_plus: ^8.0.0
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter: